In [4]:
# Insert

import numpy as np

a = np.array([10,20,30,40,50])
b = np.append(a,[90])
print(b)

[10 20 30 40 50 90]


In [11]:
a = np.array([[10,20,30],[40,50,60]])
b= np.append(a,[70,100])
print(a)
print('\n')
print(b)

[[10 20 30]
 [40 50 60]]


[ 10  20  30  40  50  60  70 100]


In [15]:
a = np.array([10,20,40,50])  # array,index,value

print(np.insert(a,2,30))

[10 20 30 40 50]


In [42]:
a = np.array([[10,20],[50,60]])
print(np.insert(a,[1,1],[30,40], axis =0))

[[10 20]
 [30 40]
 [30 40]
 [50 60]]


In [51]:
# Delete

print(a)
print('\n')
print(np.delete(a,1, axis = 0))


[[10 20]
 [50 60]]


[[10 20]]
