In [8]:
import numpy as np

a = np.array([20,30,40,50])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))


140
20
50
4
35.0
[ 20  50  90 140]
[     20     600   24000 1200000]


In [30]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)
print()
print(np.sum(price))
print('\n')
c = np.cumprod([price,quantity], axis = 0)
print(c)
print()
print(c[1].sum())


[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

1029


[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]

31270
