In [22]:
import numpy as np

a = [[10.5,20,30],[40,50,60.5],[70,80.5,90]]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))   #number of nested value
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))
print(arr.astype(str))
print(arr.astype(int))

[[10.5 20.  30. ]
 [40.  50.  60.5]
 [70.  80.5 90. ]]
(3, 3)
3
9
<class 'numpy.ndarray'>
float64
[[10.5 20.  30. ]
 [40.  50.  60.5]
 [70.  80.5 90. ]]
[['10.5' '20.0' '30.0']
 ['40.0' '50.0' '60.5']
 ['70.0' '80.5' '90.0']]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
