In [1]:
a = [10,20,30]
b =[40,50,60]
print(a+b)

[10, 20, 30, 40, 50, 60]


In [11]:
#Concatenate

import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([4,5,6])
print(np.concatenate([arr1,arr2]))

[10 20 30  4  5  6]


In [14]:
import numpy as np
arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[4,5],[6,7]])
print(np.concatenate([arr1,arr2]))

[[10 20]
 [30 40]
 [ 4  5]
 [ 6  7]]


In [23]:
print(np.concatenate([arr1,arr2],axis = 1))

[[10 20  4  5]
 [30 40  6  7]]


In [24]:
#Horizontal Concatenate

print(np.hstack([arr1,arr2]))

[[10 20  4  5]
 [30 40  6  7]]


In [36]:
#Vertical Concatenate

print(np.vstack([arr1,arr2]))

[[10 20]
 [30 40]
 [ 4  5]
 [ 6  7]]


In [40]:
a = np.array([10,20,30,40,50,60])
print (np.array_split(a,4))


[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [42]:
a = np.array([10,20,30,40,50,60])
b = np.array_split(a,3)
print(b[1])

[30 40]
