In [3]:
import numpy as np

arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])
print(arr1 + arr2)
print(np.add(arr1,arr2))

[ 60  80 100 120]
[ 60  80 100 120]


In [10]:
arr3 = np.array([[10,20],[30,40]])
arr4 = np.array([[50,60],[70,80]])
print(arr3 - arr4)
print(np.subtract(arr3,arr4))

[[-40 -40]
 [-40 -40]]
[[-40 -40]
 [-40 -40]]


In [18]:
arr3 = np.array([[10,20],[30,40]])
arr4 = np.array([[50,60],[70,80]])
print(arr3 * arr4)
print(np.multiply(arr3,arr4))

[[ 500 1200]
 [2100 3200]]
[[ 500 1200]
 [2100 3200]]


In [20]:
print(arr3/arr4)
print(np.divide(arr3,arr4))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
arr1 = np.array([5,40,50,70])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[  25 1600 2500 4900]


In [29]:
arr1 = np.array([ 25,1600,2500,4900])
print(np.sqrt(arr1))

[ 5. 40. 50. 70.]
