In [1]:
import numpy as np
# sort
arr1 = np.array([7,8,4,12,9])
print(np.sort(arr1))
print('\n')

arr2 = np.array([[6,3,9,2],[8,14,11,18]])
print(np.sort(arr2))
print('\n')

# serach
arr3 = np.array([3,4,1,7,8])
s = np.where(arr3 == 1)
print(s)
print('\n')
arr4 = np.array([23,5,20,17,6,13])
s = np.where(arr4 % 2 == 0)
print(s)
ss = np.searchsorted(arr4,17)  # first sort then search
print(ss)
print('\n')

# filter

arr5 = np.array([10,15,20,25])
f = [True,True,False,True]
new = arr5[f]
print(new)
print('\n')
arr6 = np.array([20,30,40,50,60,70,80,90,100])
fa = arr6 > 50
new = arr6[fa]
print(new)
print('\n')
arr6 = np.array([2,3,4,5,6])
fa = arr6 % 2 == 1
new = arr6[fa]
print(new)

[ 4  7  8  9 12]


[[ 2  3  6  9]
 [ 8 11 14 18]]


(array([2], dtype=int64),)


(array([2, 4], dtype=int64),)
2


[10 15 25]


[ 60  70  80  90 100]


[3 5]
